[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "J8X6Kf5b1nyeGC2XMBx4AvFiWrqCmyL8EwMNKJmKiow4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
